# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.1-cli

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      #
      # - image: redis:2.8.19

    steps:
      - checkout

      - run: 
          name: run local
          command: sudo sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && sudo sed -i 's|security.debian.org/debian-security|mirrors.ustc.edu.cn/debian-security|g' /etc/apt/sources.list
      
      - run:
          name: install cmake
          command: sudo apt update && sudo apt install -y cmake

      - run: php -f ./.circleci/prepare.php

      - run: php ./.build/phpx build && sudo php ./.build/phpx install

      - run:
          name: enable zk
          command: sudo cp .circleci/docker-php-ext-zookeeper.ini /usr/local/etc/php/conf.d/

      - run:
          name: enable swoole
          command: sudo cp .circleci/docker-php-ext-swoole.ini /usr/local/etc/php/conf.d/

      - run: php -m

      - run: ./tests/start.sh
